# AI PA1: NQueens

**Readme**

Used Python 3.9, Vs code as a development environment

## Part 1: Class definition

This is the part that you will implement. See the comments in the code and read the assignment description.

In [18]:
# import files if needed
import numpy
from math import *
import random
from simpleai.search import SearchProblem,breadth_first,uniform_cost,depth_first,limited_depth_first
from simpleai.search.viewers import WebViewer,ConsoleViewer,BaseViewer


# class definition for NQueens


class NQueens(SearchProblem):
    """ class constructor
    initializes the instance attributes N and state """
    
    def __init__(self, N): 
        self.N = N
        self.set_state()
        self.initial_state = self.state_str

        self._actions = []
        for i in range(1,self.N + 1):
            for j in range(1,self.N + 1):
                self._actions.append( ( (str(i)+".ci quenn moves to " + str(j) + ".row" ), (i,j) ) )

    """ returns a formatted string
    that represents the instance """



    def __str__(self):
        return "N: " + str(self.N) + ", state: " + self.state_str

    """ Sets the instance attribute state by displaying 
    a menu to the user. The user either enters the state 
    manually or prompts the system to generate a random state.
    Check if the input state is a valid state. """

    def set_state(self):
        question = "How dou you want to set state?"
        options = "1. Set state manually /n2. Set state randomly"

        choice = input(question + options + "Your choice: ")
        if choice == "1":
            self.state_str = str(input("enter state:"))
            while not self._is_valid(self.state_str):
                self.set_state()

        elif choice == "2":
            self.state_str = self.generate_random_state()

    """ generates and returns a valid random state """

    def generate_random_state(self):
        random_state_str = ""
        for i in range(self.N):
            random_state_str += str(random.randint(1, self.N))

        return random_state_str

    """ This is an internal function that takes a state_str as input
    and return if this is a valid state or not """


    def _is_valid(self, state_str):
        
        if len(state_str) != self.N:
            print("invalid length")
            return False    

        for letter in state_str:
            if not letter.isdigit():
                print("non digit detected")
                return False

            elif int(letter) > self.N or int(letter) < 1:
                print("index out of bound")
                return False

        return True
    """ This is the primary function of this class.
    It returns the number of attacking pairs in the board.
    12345
    """

    def count_attacking_pairs(self,state):
        board = numpy.array([[0] * self.N for _ in range(self.N)])
        self.state_str = state
        row_count = 0
        diagonal_count = 0
        total = 0

        for i in range(self.N):
            print(self.state_str)

            index = int(self.state_str[i])  
            board[:, i][self.N - index] = 1
            
        #debug
        for dim in board:
            print(dim)

        for i in range(self.N):
            for j in range(self.N):
                if board[i][j] == 1:
                    row_count += 1
            if row_count > 1:
                total += comb(row_count, 2)
            row_count = 0

        for x in range((2*self.N) - 3):

            if(x < self.N - 1):  # upper left
                a = 0
                b = x + 1
                i = a
                j = b
            else: # lower right 
                a = x - (self.N - 2)
                b = self.N - 1
                i = a
                j = b
            while i + j >= b and j >= a and i <= b:

                if board[i][j] == 1:
                    diagonal_count += 1
                i += 1
                j -= 1

            if(diagonal_count >= 2):
                total += comb(diagonal_count, 2)
            diagonal_count = 0

        for x in range((2*self.N) - 3):

            if(x < self.N - 1): # upper right 
                a = 0
                b = self.N - x - 2
                i = a
                j = b
            else: # lower left 
                a = x - (self.N - 2)
                b = 0
                i = a
                j = b

            while j <= self.N - 1 and i <= self.N - 1:

                if board[i][j] == 1:
                    diagonal_count += 1
                    
                i += 1
                j += 1

            if(diagonal_count >= 2):
                total += comb(diagonal_count, 2)
            diagonal_count = 0


        return total


    
        
    def actions(self,state):
        possible_actions = []
  
        i = 0
 
        for action in self._actions:
            #print(str(action) + " => "+str(action[1][1]) + " =? " + state[ action[1][0] - 1 ]  )
            if(action[1][1] != int(state[ action[1][0] - 1 ]) ):
                possible_actions.append(action)
                
              
        return possible_actions 


    def is_goal(self,state):
        return self.count_attacking_pairs(state) == 0 


    def result(self,state,action):

        target_row = action[1][1] 
        target_index = action[1][0] - 1
        new_state = ""
        
        for i in range(self.N):
            if i != target_index:
                new_state += state[i]
            else:
                new_state += str(target_row)
        self.state_str = new_state
        
        return new_state
               
    #debug purposes     
    def print_actions(self):
        __actions = self.actions(self.state_str)
        for action in __actions:
            print(action)


## Part 2: Testing

Do not change this part. This is the test code.

In [19]:
problem = NQueens(5)
my_viewer = BaseViewer()
print(problem.state_str)
result = breadth_first(problem,viewer=my_viewer)

print("BFS: ")
print(result.state)
print(result.path())






33332
33332
33332
33332
33332
33332
[0 0 0 0 0]
[0 0 0 0 0]
[1 1 1 1 0]
[0 0 0 0 1]
[0 0 0 0 0]
13332
13332
13332
13332
13332
[0 0 0 0 0]
[0 0 0 0 0]
[0 1 1 1 0]
[0 0 0 0 1]
[1 0 0 0 0]
23332
23332
23332
23332
23332
[0 0 0 0 0]
[0 0 0 0 0]
[0 1 1 1 0]
[1 0 0 0 1]
[0 0 0 0 0]
43332
43332
43332
43332
43332
[0 0 0 0 0]
[1 0 0 0 0]
[0 1 1 1 0]
[0 0 0 0 1]
[0 0 0 0 0]
53332
53332
53332
53332
53332
[1 0 0 0 0]
[0 0 0 0 0]
[0 1 1 1 0]
[0 0 0 0 1]
[0 0 0 0 0]
31332
31332
31332
31332
31332
[0 0 0 0 0]
[0 0 0 0 0]
[1 0 1 1 0]
[0 0 0 0 1]
[0 1 0 0 0]
32332
32332
32332
32332
32332
[0 0 0 0 0]
[0 0 0 0 0]
[1 0 1 1 0]
[0 1 0 0 1]
[0 0 0 0 0]
34332
34332
34332
34332
34332
[0 0 0 0 0]
[0 1 0 0 0]
[1 0 1 1 0]
[0 0 0 0 1]
[0 0 0 0 0]
35332
35332
35332
35332
35332
[0 1 0 0 0]
[0 0 0 0 0]
[1 0 1 1 0]
[0 0 0 0 1]
[0 0 0 0 0]
33132
33132
33132
33132
33132
[0 0 0 0 0]
[0 0 0 0 0]
[1 1 0 1 0]
[0 0 0 0 1]
[0 0 1 0 0]
33232
33232
33232
33232
33232
[0 0 0 0 0]
[0 0 0 0 0]
[1 1 0 1 0]
[0 0 1 0 1]
[0 0 0 0 0]
3343